### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [jotacehd/prj-rev-bwfs-dasmoto#6]
https://github.com/jotacehd/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/resources/css/style.css#L13

If you'd used `div` tags, you could write a more readable and maintainable CSS selector for these styles. For example:

```css
.product h2 {
  font-size: 32px;
  font-weight: bold;
  color:#fff;
}
```

https://github.com/jotacehd/prj-rev-bwfs-dasmoto/blob/master/ArtsCrafts/resources/css/style.css#L33-L36

You're repeating this style in several rules but without it you could completely remove this last rule.

Avoid the repetition and ensure the style gets applied by putting it in a more general selector like `*`.

```css
* {
  font-family: Helvetica;
}
```
